name: Auto commit

on:
  schedule:
    - cron: '0 2 * * *'  # 09:00 (UTC+7)
    - cron: '30 6 * * *' # 13:30 (UTC+7)
    - cron: '12 9 * * *' # 16:12 (UTC+7)
    - cron: '0 11 * * *' # 18:00 (UTC+7)

jobs:
  auto_commit:
    name: 'Auto push a commit to my repo'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create sample file with just timestamp
      run: date +%s >> JustForFun.txt
    - name: Commit file
      run: |
          git config --global user.name "Phuong Van"
          git config --global user.email "vnphuong16@users.noreply.github.com"
          git add JustForFun.txt
          git commit -am "Automated report"
          git push
